### ISSUE TITLE
QGC glitches and shows 2 drones

### ISSUE THREAD

**Issue by mommotti** [JonasVautherin/px4-gazebo-headless#21]
I start it with this command:
docker run --rm -it --env PX4_HOME_LAT=my_chosen_lat --env PX4_HOME_LON=my_chosen_lon --env PX4_HOME_ALT=488.0 jonasvautherin/px4-gazebo-headless:1.11.0

And QGC shows both the default drone in Zurich and the one with my coordinates:

[Here is a GIF of the issue](https://gifyu.com/image/ryPz)

**Comment by julianoes** [comment]
Could it be that you have some other drone in the network sending out MAVLink? Or a real drone connected as well?

**Comment by mommotti** [comment]
It was the Raspberry sending data! Thanks
