### ISSUE TITLE
Question: Deploying a px4-gazebo-headless container on an AWS EC2 instance and connecting mavsdk and QGC from a remote PC

### ISSUE THREAD

**Issue by SaigaGentil** [JonasVautherin/px4-gazebo-headless#25]
I am trying to setup a px4-gazebo-headless container in docker on an AWS Ubuntu EC2 instance and connect QGC on my local PC via the EC2's public IP. So far I have been unsuccessful. I have checked the security groups and everything, traffic should be allowed to flow, but still it doesn't work, and I believe that I am missing something.

How can I deploy a px4-gazebo-headless container on an AWS EC2 instance such that I can connect to a ground control station like QGC and mavsdk from a remote PC via the EC2's public IP address...

**Comment by julianoes** [comment]
What exactly have you tried? And did you forward the ports, etc.
