### ISSUE TITLE
Publish image for `arm64`

### ISSUE THREAD

**Issue by Sitin** [JonasVautherin/px4-gazebo-headless#26]
At the moment it is not possible to run the existing image on `arm64` and OS X due to a qemu bug (anyway, it would be painfully slow).

Fortunately I've just successfully built an image for `amd64` (OS X) with one minor amendment:

```
RUN pip3 install --upgrade pip && \   # pip should be upgraded to support multiple patforms
    pip3 install empy \
    ...
```

It would be helpful if `arm64` image will be published on Docker Hub. It can be done by a [simple change](https://github.com/marketplace/actions/run-on-architecture) in GitHub pipelines config.

**Comment by julianoes** [comment]
I'd suggest to make a PR here that adds what you need to CI.

**Comment by Sitin** [comment]
I've added PR: #27.

**Comment by julianoes** [comment]
Thanks @Sitin.
