### ISSUE TITLE
Update tags to include ARM64 build

### ISSUE THREAD

**Issue by Sitin** [JonasVautherin/px4-gazebo-headless#29]
Could you please update the tag to include the recently added build for arm64.

**Comment by JonasVautherin** [comment]
Latest is already available: https://hub.docker.com/r/jonasvautherin/px4-gazebo-headless/tags

Isn't that enough? I was planning on just waiting until PX4 1.13.1, which will include it.

**Comment by Sitin** [comment]
Makes sense.
