### ISSUE TITLE
Connection to Gazebo simulator

### ISSUE THREAD

**Issue by ldezons** [JonasVautherin/px4-gazebo-headless#38]
Hello, 

The container is well connecting to QGC (macos) however gazebo is not starting (the computer's version or the container's one). Would you know how to solve this?

**Comment by JonasVautherin** [comment]
What do you mean, "gazebo is not starting"?

**Comment by ldezons** [comment]
I mean that the simulation is not connected to the gazebo client in which you can see the drone and its environment

**Comment by JonasVautherin** [comment]
Oh... `px4-gazebo-headless` runs in headless mode, which means that there is no UI. You will only see the PX4 shell, not gazebo.

Does that make sense?

**Comment by ldezons** [comment]
Okay I see. Many thanks!
